site/books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BookModelView.as_view(), name='index'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherLsit.as_view(), name='publisher_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),

]

site/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('books/', include('books.urls')),
    path('', views.HomeView.as_view(), name = 'home'),
]

site/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:question_id>/', views.detail, name ='detail'),
    path('<int:question_id>/results/', views.results, name = 'results'),
    path('<int:question_id>/vote/', views.vote, name = 'vote'),
]

site/books/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=100 )
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models .CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

site/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

site/books/views.py
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from .models import Book, Author, Publisher

class BookModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context

# -- ListView
class BookList(ListView):
    model = Book

class AuthorList(ListView):
    model = Author

class PublisherLsit(ListView):
    model = Publisher


# -- DetailView
class BookDetail(DetailView):
    model = Book

class AuthorDetail(DetailView):
    model = Author

class PublisherDetail(DetailView):
    model = Publisher

site/mysite/views.py
from django.views.generic.base import TemplateView

# TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['app_list'] = ['polls', 'books']
        return context

site/polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.generic import View

def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'polls/detail.html', { 'question': question })

def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)

    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except (KeyError , Choice.DoesNotExist):
        return render(request, 'polls/detail.html',  {
            'question': question,
            'error_message': "You didn't select a choice",
        })

    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args = (question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'polls/results.html', {'question':question})

class MyView(View):
    def get(self, request ):
        return HttpResponse('result')

site/books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h2>{{ object.name }}</h2>
    <br>
    <p>salutation : {{ object.salutation }}</p>
    <li>Email : {{ object.email }}</li>
{% endblock content %}

site/books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list %}
            <li><a href ="{% url  'books:author_detail' author.id %}" >{{ author.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

site/books/templates/books/book_base.html
{% extends "base.html" %}

<title>{% block title %} Books Application Site {% endblock %}</title>

{% block sidebar %}
{{block.super}}

<ul>
    <li><a href = "/books/"> Books_Home</a></li>
</ul>
{% endblock %}

site/books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h2>{{ obejct.title }}</h2>
    <br>
    <li>Authors:
        {% for author in object.authors.all %}
            {{ author }}
            {% if not forloop.last %},{% else %}{% endif %}
        {% endfor %}
    </li>
    <li>Publisher : {{ object.publisher }}</li>
    <li>Publication date : {{ object.publication_date }}</li>
{% endblock content %}

site/books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href ="{% url  'books:book_detail' book.id %}" >{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

site/books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in model_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
            <li><a href ="{% url  urlvar %}" >{{ modelname }}</a></li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}

site/books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h2>{{ object.name }}</h2>
    <p>Website : {{ object.website }}</p>
    <li>Address : {{ object.address }}</li>
{% endblock content %}

site/books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href ="{% url  'books:publisher_detail' publisher.id %}" >{{ publisher.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

site/polls/templates/polls/detail.html
<h1>{{ question.question_text}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type = "radio" name = "choice" id = "choice{{ forloop.counter }}" value="{{choice.id}}" />
        <label for = "choice {{ forloop.counter }}"> {{ choice.choice_text }}</label></br>
    {% endfor %}

    <input type = "submit" value = "Vote" />
</form>

site/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="/polls/{{ question.id }}/">{{ question.question_text}}</a> </li>
        {% endfor %}
    </ul>
{% else %}
    <p> No polls are avaiable. </p>
{% endif %}

site/polls/templates/polls/results.html
<h1> {{question.question_id}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} - {{ choice.votes }} vote {{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">VOTE again?</a>

site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel = "stylesheet" href = "{% static 'admin/css/base.css' %}" />
    <title>{% block title %} My Amazing Site {% endblock %}</title>

</head>
<body>
    <div id = "sidebar">
        {% block sidebar %}
        <ul>
            <li><a href = "/"> Project_Home </a></li>
            <li><a href = "/admin/"> Admin </a></li>
        </ul>
        {%endblock%}
        <br>
    </div>

    <div id = "content">
        {%block content %} {% endblock %}
    </div>
</body>
</html>

site/templates/base_books.html
{% extends "base.html" %}
<title>
    {% block title %}
        Books Application Site
    {% endblock %}
</title>
{% block sidebar %}
    {{block.super}}
    <ul>
        <li><a href ="/books/">Books_Home</a></li>
    </ul>
{% endblock %}

site/templates/home.html
{% extends "base.html" %}
{% block content %}
    <h2>shkim Django Applications</h2>
    <ul>
        {% for appname in app_list %}
            {% with appname|add:":"|add:"index" as urlvar %}
                <li>
                    <a href = "{% url urlvar %}">{{ appname }}</a>
                </li>
            {% endwith%}
        {% endfor %}    
    </ul>
{% endblock content %}